name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      date:
        required: true
        default: "Please enter the date of submission (e.g. 12/01)"
      title:
        default: "Please enter the title"
      author:
        default: "Please enter the author's name"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Show inputs
      run: |
        echo "target: ${{ github.event.inputs.date }}"
        echo "message: ${{ github.event.inputs.title }}"
        echo "dryrun: ${{ github.event.inputs.author }}"
        go version
