name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      date:
        required: true
        description: "Please enter the date of submission (e.g. 12/01)"
      title:
        description: "Please enter the title"
      author:
        description: "Please enter the author's name"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Show inputs
      run: |
        echo "target: ${{ github.event.inputs.date }}"
        echo "message: ${{ github.event.inputs.title }}"
        echo "dryrun: ${{ github.event.inputs.author }}"
    - name: run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $GITHUB_REF_NAME
        git switch -c fix/tmp4
        echo $GITHUB_REF_NAME
        git switch $GITHUB_REF_NAME
        echo $GITHUB_REF_NAME
        # git config user.name  "[bot] ${GITHUB_ACTOR}"
        # git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        # git switch -c fix/tmp3
        # # go run ./action.go -date=12/01 -title=tmp
        # touch file3.md
        # git add file3.md
        # git commit -m "tmp2"
        # # hub push origin fix/tmp2
        # # git switch -
        # hub pull-request -p -b main -m test title
