name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      date:
        required: true
        default: "Please enter the date of submission (e.g. 12/01)"
      title:
        default: "Please enter the title"
      author:
        default: "Please enter the author's name"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Show inputs
      run: |
        echo "target: ${{ github.event.inputs.date }}"
        echo "message: ${{ github.event.inputs.title }}"
        echo "dryrun: ${{ github.event.inputs.author }}"
    - name: run
      run: |
        go run ./action.go -date=12/01 -title=tmp
