name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      date:
        required: true
        default: "Please enter the date of submission (e.g. 12/01)"
      title:
        default: "Please enter the title"
      author:
        default: "Please enter the author's name"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Show inputs
      run: |
        echo "target: ${{ github.event.inputs.date }}"
        echo "message: ${{ github.event.inputs.title }}"
        echo "dryrun: ${{ github.event.inputs.author }}"
    - name: run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name  "[bot] ${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git switch -c fix/tmp
        # go run ./action.go -date=12/01 -title=tmp
        touch file2.md
        git add file2.md
        git commit -m "tmp2"
        #hub push origin fix/tmp
        hub pull-request -p --base OWNER:main --draft -m test title
