name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      date:
        required: true
        description: "Please enter the date of submission (e.g. 12/01)"
      title:
        description: "Please enter the title"
      author:
        description: "Please enter the author's name"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Show inputs
      run: |
        echo "date: ${{ github.event.inputs.date }}"
        echo "title: ${{ github.event.inputs.title }}"
        echo "author: ${{ github.event.inputs.author }}"
    - name: run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         go run ./action.go \
           -date=${{ github.event.inputs.date }} \
           -title=${{ github.event.inputs.title }} \
           -author=${{ github.event.inputs.author }}
